name: autobooking
services:
  bot-autobooking:
    container_name: aimharder-auto-booking
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
    shm_size: '2gb'
    environment:
      - NODE_ENV=${NODE_ENV}
      - SIMULATION_MODE=${SIMULATION_MODE}
      - SEND_TELEGRAM_NOTIFICATION=${SEND_TELEGRAM_NOTIFICATION}
      - EXECUTE_JOB=${EXECUTE_JOB}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - DB_PORT=5984
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - TZ=${TZ}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - couchdb-autobookings
    networks:
      - network-autobookings

  couchdb-autobookings:
    image: couchdb:3
    container_name: couchdb-autobookings
    restart: always
    ports:
      - "${DB_PORT}:5984"
    environment:
      - COUCHDB_USER=${DB_USER}
      - COUCHDB_PASSWORD=${DB_PASSWORD}
      - COUCHDB_NODENAME=127.0.0.1
      - COUCHDB_SECRET=monster
      - TZ=${TZ}
    volumes:
      - couchdb_auto_bookings_data:/opt/couchdb/data
    networks:
      - network-autobookings

volumes:
  couchdb_auto_bookings_data:
    name: couchdb_autobookings_data

networks:
  network-autobookings:
    name: network-autobookings
