services:
  bot:
    container_name: aimharder-auto-booking
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
    shm_size: '2gb'
    environment:
      - NODE_ENV=${NODE_ENV}
      - SIMULATION_MODE=${SIMULATION_MODE}
      - SEND_TELEGRAM_NOTIFICATION=${SEND_TELEGRAM_NOTIFICATION}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
