services:
  bot:
    container_name: aimharder-auto-booking
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
    shm_size: '2gb'
    environment:
      - NODE_ENV=${NODE_ENV}
      - SIMULATION_MODE=${SIMULATION_MODE}
      - SEND_TELEGRAM_NOTIFICATION=${SEND_TELEGRAM_NOTIFICATION}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - couchdb-bookings

  couchdb-bookings:
    image: couchdb:3
    container_name: couchdb-bookings
    restart: always
    ports:
      - "${DB_PORT}:5984"
    environment:
      COUCHDB_USER: ${DB_USER}
      COUCHDB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - couchdb_bookings_data:/opt/couchdb/data

volumes:
  couchdb_bookings_data:
